### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by op01**

### CODE REVIEW

**Comment by kamikazechaser** [comment]
We are simply importing the library, no typo here.

**Comment by op01** [comment]
In usage section of README file, you are importing the library and assigning it to variable `tgresolve`. 
```js
const tgresolve = require("tg-resolve");
```
But later you refer the variable as `tgresolver` (please note the extra 'r') in 
```js
const resolver = new tgresolver.Tgresolve(token);
```
The correct should be like line 20-21 of example.js file.
```js
const tgresolve = require(".");
const tgresolver = new tgresolve.Tgresolve(token, { url });
```

**Comment by kamikazechaser** [comment]
My bad, I just realized it.

**Comment by kamikazechaser** [comment]
I'm currently on my phone, I will merge it as soon as I am on my PC. Thanks.

**Pull request merged**
